[book]
authors = ["realcpf"]
language = "zh-CN"
multilingual = false
src = "src"
title = "book"

[build]
build-dir = "book"

[output.html.playpen]
editable = true
copy-js = true

[preprocessor.index]

[preprocessor.links]

[output.html.search]
enable = true
limit-results = 20
teaser-word-count = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true

[output.html]
theme="book"
default-theme = "rust"
